In [2]:
library("lme4")
library("margins")
library("stargazer")
library("emmeans")
library("ggeffects")
library("broom")
library("broom.mixed")
library("MASS")
library("pscl")
library("fixest")
library("marginaleffects")
library("modelsummary")
library("glmmTMB")
library("dplyr")

In [3]:
main_path <- "/home/20250114zmz_kd/"
data <- read.csv(paste0(main_path, "UseBSForNot/MergeInsthData_1211.csv"))
dim(data)

[1] 3227892      78

In [4]:
print(names(data))

 [1] "X"
 [2] "work_id"
 [3] "fac_pub"
 [4] "year"
 [5] "paper_type"
 [6] "paper_language"
 [7] "nwbin"
 [8] "new_word_reuse_times"
 [9] "npbin"
[10] "new_phrase_reuse_times"
[11] "novelbin"
[12] "rao_stirling"
[13] "author_id"
[14] "author_position"
[15] "institution_id"
[16] "country_code"
[17] "country"
[18] "num_author_log"
[19] "num_inst_log"
[20] "num_country_log"
[21] "num_reference_log"
[22] "timescited5_log"
[23] "timescited10_log"
[24] "timescitedall_log"
[25] "ab_length_log"
[26] "leadership_global_class"
[27] "mean_career_age_log"
[28] "inst_h_index_log"
[29] "source_id"
[30] "source_h_index_log"
[31] "source_type"
[32] "core_source"
[33] "Agricultural.and.Biological.Sciences"
[34] "Arts.and.Humanities"
[35] "Biochemistry..Genetics.and.Molecular.Biology"
[36] "Business..Management.and.Accounting"
[37] "Chemical.Engineering"
[38] "Chemistry"
[39] "Computer.Science"
[40] "Decision.Sciences"
[41] "Dentistry"
[42] "Earth.and.Planetary.Sciences"
[43] "Economics..Econometrics.and.Finance"
[44] "Energy"
[45] "Engineering"
[46] "Environmental.Science"
[47] "Health.Professions"
[48] "Immunology.and.Microbiology"
[49] "Materials.Science"
[50] "Mathematics"
[51] "Medicine"
[52] "Neuroscience"
[53] "Nursing"
[54] "Pharmacology..Toxicology.and.Pharmaceutics"
[55] "Physics.and.Astronomy"
[56] "Psychology"
[57] "Social.Sciences"
[58] "Veterinary"
[59] "domain_Health.Sciences"
[60] "domain_Life.Sciences"
[61] "domain_Physical.Sciences"
[62] "domain_Social.Sciences"
[63] "Atyp_10pct_Z"
[64] "new_word"
[65] "new_phrase"
[66] "DI5"
[67] "DI10"
[68] "num_author"
[69] "num_inst"
[70] "num_country"
[71] "num_reference"
[72] "timescited5"
[73] "timescited10"
[74] "timescitedall"
[75] "source_h_index"
[76] "mean_career_age"
[77] "ab_length"
[78] "inst_h_index"

In [5]:
colSums(is.na(data))

                                           X
                                           0
                                     work_id
                                           0
                                     fac_pub
                                           0
                                        year
                                           0
                                  paper_type
                                           0
                              paper_language
                                           0
                                       nwbin
                                           0
                        new_word_reuse_times
                                           0
                                       npbin
                                           0
                      new_phrase_reuse_times
                                           0
                                    novelbin
                                           0
                                rao_stirling
                                      303430
                                   author_id
                                           0
                             author_position
                                           0
                              institution_id
                                           0
                                country_code
                                           0
                                     country
                                           0
                              num_author_log
                                           0
                                num_inst_log
                                           0
                             num_country_log
                                           0
                           num_reference_log
                                           0
                             timescited5_log
                                      107147
                            timescited10_log
                                      163886
                           timescitedall_log
                                           0
                               ab_length_log
                                           0
                     leadership_global_class
                                           0
                         mean_career_age_log
                                           0
                            inst_h_index_log
                                           6
                                   source_id
                                           0
                          source_h_index_log
                                           0
                                 source_type
                                           0
                                 core_source
                                           0
        Agricultural.and.Biological.Sciences
                                           0
                         Arts.and.Humanities
                                           0
Biochemistry..Genetics.and.Molecular.Biology
                                           0
         Business..Management.and.Accounting
                                           0
                        Chemical.Engineering
                                           0
                                   Chemistry
                                           0
                            Computer.Science
                                           0
                           Decision.Sciences
                                           0
                                   Dentistry
                                           0
                Earth.and.Planetary.Sciences
                                           0
         Economics..Econometrics.and.Finance
                                           0
                                      Energy
                                           0
                                 Engineering
                                           0
                       Environmental.Science
                                           0
                          Health.Professions
                                           0
                 Immunology.and.Microbiology
                                           0
                           Materials.Science
                                           0
                                 Mathematics
                                           0
                                    Medicine
                                           0
                                Neuroscience
                                           0
                                     Nursing
                                           0
  Pharmacology..Toxicology.and.Pharmaceutics
                                           0
                       Physics.and.Astronomy
                                           0
                                  Psychology
                                           0
                             Social.Sciences
                                           0
                                  Veterinary
                                           0
                      domain_Health.Sciences
                                           0
                        domain_Life.Sciences
                                           0
                    domain_Physical.Sciences
                                           0
                      domain_Social.Sciences
                                           0
                                Atyp_10pct_Z
                                      413497
                                    new_word
                                      363512
                                  new_phrase
                                      363512
                                         DI5
                                     1516264
                                        DI10
                                     1637246
                                  num_author
                                           0
                                    num_inst
                                           0
                                 num_country
                                           0
                               num_reference
                                           0
                                 timescited5
                                      107147
                                timescited10
                                      163886
                               timescitedall
                                           0
                              source_h_index
                                           0
                             mean_career_age
                                           0
                                   ab_length
                                           0
                                inst_h_index
                                           6

In [6]:
# 把所有无限值替换成 NA
data[sapply(data, is.infinite)] <- NA

In [7]:
data <- data[!is.na(data$Atyp_10pct_Z), ]
dim(data)
data <- data[data$num_reference >=5, ]
dim(data)

[1] 2814103      78

[1] 2760385      78

In [8]:
# data <- data[data$ab_length > 0, ]
# dim(data)
data <- data[data$year >= 1950, ]
dim(data)

[1] 2760385      78

In [9]:
# 找出所有包含无限值的行和列
inf_mask <- sapply(data, function(col) is.infinite(col))
rows_with_inf <- apply(inf_mask, 1, any)  # 哪些行至少有一个Inf
cols_with_inf <- colnames(data)[apply(inf_mask, 2, any)]  # 哪些列有Inf

# 打印包含无限值的行数和列名
cat("包含无限值的行数:", sum(rows_with_inf), "\n")
cat("包含无限值的列名:", paste(cols_with_inf, collapse = ", "), "\n")

# 查看这些行具体内容
data_filt_with_inf <- data[rows_with_inf, c(cols_with_inf), drop=FALSE]
print(data_filt_with_inf)

包含无限值的行数: 0
包含无限值的列名:
data frame with 0 columns and 0 rows

In [10]:
data$leadership_global_class <- factor(data$leadership_global_class)
data <- within(data, leadership_global_class <- relevel(leadership_global_class, ref = 'shared'))
data$fac_pub <- factor(data$fac_pub)
data <- within(data, fac_pub <- relevel(fac_pub, ref = 'NonBSF'))
data$core_source <- factor(data$core_source)
data <- within(data, core_source <- relevel(core_source, ref = 'NonCore'))
data$year <- as.factor(data$year)

In [11]:
# variable type
paper_level <- "num_author_log + num_inst_log + num_country_log + num_reference_log + leadership_global_class + mean_career_age_log + inst_h_index_log" 
journal_level <- "source_h_index_log + core_source"
disciplines <- "Arts.and.Humanities + Biochemistry..Genetics.and.Molecular.Biology + Business..Management.and.Accounting + Chemical.Engineering + 
 Chemistry + Computer.Science + Decision.Sciences + Dentistry + Earth.and.Planetary.Sciences + 
Economics..Econometrics.and.Finance + Energy + Engineering + Environmental.Science + Health.Professions + 
Immunology.and.Microbiology + Materials.Science + Mathematics + Medicine + Neuroscience + Nursing +
Pharmacology..Toxicology.and.Pharmaceutics + Physics.and.Astronomy + Psychology + Social.Sciences + Veterinary "

In [12]:
fml <- as.formula(
  paste0("novelbin ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_ps <- feglm(fml, data = data[(data$domain_Physical.Sciences == 1), ], family = binomial("logit"), vcov = "iid")
summary(model_ps)

NOTES: 3 observations removed because of NA values (RHS: 3).
       20,215/0 fixed-effects (78,545 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novelbin
Observations: 2,236,396
Fixed-effects: author_id: 55,424,  year: 76
Standard-errors: IID
                                              Estimate Std. Error    z value
fac_pubBSF                                    0.074731   0.006671  11.202080
num_author_log                                0.211550   0.005207  40.626516
num_inst_log                                 -0.003943   0.006613  -0.596263
num_country_log                              -0.293126   0.009664 -30.333097
num_reference_log                             0.146196   0.003269  44.724004
leadership_global_classallNorth               0.138545   0.009386  14.760193
leadership_global_classallSouth              -0.053631   0.015025  -3.569560
mean_career_age_log                           0.004271   0.005411   0.789263
inst_h_index_log                             -0.016366   0.004186  -3.909818
source_h_index_log                           -0.028386   0.002448 -11.593961
core_sourceCore                               0.043512   0.012986   3.350640
Arts.and.Humanities                           0.681922   0.031874  21.394345
Biochemistry..Genetics.and.Molecular.Biology  0.651814   0.006807  95.756869
Business..Management.and.Accounting           0.333623   0.043853   7.607751
Chemical.Engineering                          0.087880   0.007913  11.106133
Chemistry                                     0.120377   0.005259  22.889008
Computer.Science                              0.425670   0.011821  36.009078
Decision.Sciences                             0.494139   0.033880  14.584823
Dentistry                                     0.851894   0.043187  19.725834
Earth.and.Planetary.Sciences                  0.237296   0.007917  29.971618
Economics..Econometrics.and.Finance           0.619741   0.044571  13.904645
Energy                                        0.113171   0.008022  14.107002
Engineering                                   0.222193   0.004539  48.952873
Environmental.Science                         0.483843   0.007755  62.388414
Health.Professions                            0.549802   0.038127  14.420117
Immunology.and.Microbiology                   0.615516   0.030270  20.333863
Materials.Science                             0.064834   0.004502  14.402209
Mathematics                                   0.200829   0.023459   8.560971
Medicine                                      0.664238   0.008752  75.898144
Neuroscience                                  0.711039   0.017588  40.427338
Nursing                                       0.755377   0.029052  26.000402
Pharmacology..Toxicology.and.Pharmaceutics    0.210957   0.020110  10.490176
Physics.and.Astronomy                        -0.099052   0.005461 -18.138183
Psychology                                    0.317654   0.055631   5.710049
Social.Sciences                               0.634555   0.035472  17.889089
Veterinary                                    0.685037   0.106901   6.408155
                                               Pr(>|z|)
fac_pubBSF                                    < 2.2e-16 ***
num_author_log                                < 2.2e-16 ***
num_inst_log                                 5.5100e-01
num_country_log                               < 2.2e-16 ***
num_reference_log                             < 2.2e-16 ***
leadership_global_classallNorth               < 2.2e-16 ***
leadership_global_classallSouth              3.5758e-04 ***
mean_career_age_log                          4.2996e-01
inst_h_index_log                             9.2366e-05 ***
source_h_index_log                            < 2.2e-16 ***
core_sourceCore                              8.0625e-04 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          2.7891e-14 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                             < 2.2e-16 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                   < 2.2e-16 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   1.1294e-08 ***
Social.Sciences                               < 2.2e-16 ***
Veterinary                                   1.4729e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -1,180,441.7   Adj. Pseudo R2: 0.145909
           BIC:  3,172,825.9     Squared Cor.: 0.223175

In [13]:
paper_vars <- c("num_author_log", "num_inst_log", "num_country_log",
                "num_reference_log", "leadership_global_class",
                "mean_career_age_log", "inst_h_index_log" )


journal_vars <- c("source_h_index_log", "core_source")

disciplines <- c("Arts.and.Humanities", "Biochemistry..Genetics.and.Molecular.Biology", "Business..Management.and.Accounting",
                 "Chemical.Engineering", "Chemistry", "Computer.Science", "Decision.Sciences", "Dentistry",
                 "Earth.and.Planetary.Sciences", "Economics..Econometrics.and.Finance", "Energy", "Engineering",
                 "Environmental.Science + Health.Professions", "Immunology.and.Microbiology", "Materials.Science", "Mathematics",
                 "Medicine", "Neuroscience", "Nursing", "Pharmacology..Toxicology.and.Pharmaceutics", "Physics.and.Astronomy",
                 "Psychology", "Social.Sciences", "Veterinary")

In [14]:
MEs = ggemmeans(model_ps, terms=c('fac_pub'), typical='median')

In [15]:
MEs

  x      predicted std.error  conf.low  conf.high group
1 NonBSF 0.2747726 0.03536667 0.2611773 0.2887991 1
2 BSF    0.2899123 0.03536021 0.2758553 0.3043845 1

In [16]:
fname = paste0(main_path, "UseBSForNot/predict_ns_1211_ps.csv")
write.csv(MEs, fname, row.names = FALSE)

In [17]:
fml <- as.formula(
  paste0("novelbin ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_ls <- feglm(fml, data = data[(data$domain_Life.Sciences == 1), ], family = binomial("logit"), vcov = "iid")
summary(model_ls)

Warning message in formula.character(object, env = baseenv()):
“Using formula(x) is deprecated when x is a character vector of length > 1.
  Consider formula(paste(x, collapse = " ")) instead.”
NOTE: 16,802/0 fixed-effects (44,296 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novelbin
Observations: 683,985
Fixed-effects: author_id: 27,091,  year: 75
Standard-errors: IID
                                 Estimate Std. Error    z value   Pr(>|z|)
fac_pubBSF                       0.055030   0.012184   4.516442 6.2887e-06 ***
num_author_log                   0.434828   0.008819  49.308389  < 2.2e-16 ***
num_inst_log                     0.059433   0.011308   5.255762 1.4741e-07 ***
num_country_log                 -0.209936   0.017055 -12.309423  < 2.2e-16 ***
num_reference_log                0.272756   0.006136  44.452298  < 2.2e-16 ***
leadership_global_classallNorth  0.060645   0.020574   2.947699 3.2015e-03 **
leadership_global_classallSouth -0.012318   0.032691  -0.376790 7.0633e-01
mean_career_age_log              0.122701   0.009507  12.906676  < 2.2e-16 ***
inst_h_index_log                -0.084335   0.007486 -11.265917  < 2.2e-16 ***
source_h_index_log              -0.095956   0.004236 -22.651096  < 2.2e-16 ***
core_sourceCore                  0.200423   0.030486   6.574318 4.8877e-11 ***
Arts.and.Humanities              0.166808   0.102704   1.624165 1.0434e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood:  -377,494.7   Adj. Pseudo R2: 0.145313
           BIC: 1,120,131.1     Squared Cor.: 0.251357

In [18]:
MEs = ggemmeans(model_ls, terms=c('fac_pub'), typical='median')

In [19]:
MEs

  x      predicted std.error  conf.low  conf.high group
1 NonBSF 0.5368261 0.06506337 0.5050123 0.5683429 1
2 BSF    0.5504777 0.06521243 0.5186881 0.5818604 1

In [20]:
fname = paste0(main_path, "UseBSForNot/predict_ns_1211_ls.csv")
write.csv(MEs, fname, row.names = FALSE)

In [21]:
fml <- as.formula(
  paste0("novelbin ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_hs <- feglm(fml, data = data[(data$domain_Health.Sciences == 1), ], family = binomial("logit"), vcov = "iid")
summary(model_hs)

Warning message in formula.character(object, env = baseenv()):
“Using formula(x) is deprecated when x is a character vector of length > 1.
  Consider formula(paste(x, collapse = " ")) instead.”
NOTES: 1 observation removed because of NA values (RHS: 1).
       16,494/0 fixed-effects (37,598 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novelbin
Observations: 337,939
Fixed-effects: author_id: 18,925,  year: 75
Standard-errors: IID
                                 Estimate Std. Error   z value   Pr(>|z|)
fac_pubBSF                       0.191439   0.018946 10.104461  < 2.2e-16 ***
num_author_log                   0.402583   0.012315 32.691391  < 2.2e-16 ***
num_inst_log                     0.065305   0.015225  4.289466 1.7910e-05 ***
num_country_log                 -0.195855   0.023574 -8.308164  < 2.2e-16 ***
num_reference_log                0.447062   0.008820 50.685642  < 2.2e-16 ***
leadership_global_classallNorth  0.116812   0.029545  3.953755 7.6934e-05 ***
leadership_global_classallSouth  0.082914   0.045610  1.817886 6.9082e-02 .
mean_career_age_log              0.108324   0.014105  7.679601 1.5958e-14 ***
inst_h_index_log                -0.037008   0.010155 -3.644111 2.6832e-04 ***
source_h_index_log              -0.061526   0.006154 -9.998024  < 2.2e-16 ***
core_sourceCore                  0.199173   0.040212  4.953101 7.3040e-07 ***
Arts.and.Humanities              0.097375   0.114930  0.847260 3.9685e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -189,687.4   Adj. Pseudo R2: 0.107361
           BIC:  621,396.7     Squared Cor.: 0.235447

In [22]:
MEs = ggemmeans(model_hs, terms=c('fac_pub'), typical='median')
MEs

  x      predicted std.error  conf.low  conf.high group
1 NonBSF 0.5773487 0.08971947 0.5339606 0.6195752 1
2 BSF    0.6232435 0.09028221 0.5808803 0.6638030 1

In [23]:
fname = paste0(main_path, "UseBSForNot/predict_ns_1211_hs.csv")
write.csv(MEs, fname, row.names = FALSE)

In [24]:
fml <- as.formula(
  paste0("novelbin ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_ss <- feglm(fml, data = data[(data$domain_Social.Sciences == 1), ], family = binomial("logit"), vcov = "iid")
summary(model_ss)

Warning message in formula.character(object, env = baseenv()):
“Using formula(x) is deprecated when x is a character vector of length > 1.
  Consider formula(paste(x, collapse = " ")) instead.”
NOTES: 1 observation removed because of NA values (RHS: 1).
       9,528/6 fixed-effects (14,305 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novelbin
Observations: 26,000
Fixed-effects: author_id: 3,308,  year: 68
Standard-errors: IID
                                 Estimate Std. Error   z value   Pr(>|z|)
fac_pubBSF                       0.590227   0.091281  6.466058 1.0059e-10 ***
num_author_log                   0.377230   0.054437  6.929618 4.2198e-12 ***
num_inst_log                    -0.057527   0.066008 -0.871509 3.8348e-01
num_country_log                 -0.382890   0.091946 -4.164269 3.1235e-05 ***
num_reference_log                0.282975   0.030407  9.306158  < 2.2e-16 ***
leadership_global_classallNorth  0.075818   0.092977  0.815451 4.1481e-01
leadership_global_classallSouth -0.082363   0.128364 -0.641639 5.2111e-01
mean_career_age_log              0.006393   0.055139  0.115937 9.0770e-01
inst_h_index_log                 0.013348   0.034633  0.385420 6.9993e-01
source_h_index_log               0.102373   0.022843  4.481582 7.4092e-06 ***
core_sourceCore                  0.020737   0.102735  0.201852 8.4003e-01
Arts.and.Humanities              0.270613   0.071133  3.804307 1.4220e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -14,585.9   Adj. Pseudo R2: -0.00137
           BIC:  63,603.5     Squared Cor.:  0.235781

In [25]:
MEs = ggemmeans(model_ss, terms=c('fac_pub'), typical='median')
MEs

  x      predicted std.error conf.low  conf.high group
1 NonBSF 0.3008051 0.3163430 0.1879345 0.4443698 1
2 BSF    0.4370263 0.3228685 0.2919256 0.5937696 1

In [26]:
fname = paste0(main_path, "UseBSForNot/predict_ns_1211_ss.csv")
write.csv(MEs, fname, row.names = FALSE)

In [27]:
model1 <- model_ps
model2 <- model_ls
model3 <- model_hs
model4 <- model_ss

country_level_reg <- etable(
    list(model1, model2, model3, model4),
    keep = c("fac_pub", paper_vars, journal_vars ),
    se = "iid",
    # cluster = ~ paper_year + paper_field,
    tex = TRUE,
    digits = 3
)

# writeLines(country_level_reg, con = "selfpromt_reg_1014.tex")

In [28]:
country_level_reg

\begingroup
\centering
\begin{tabular}{lcccc}
   \tabularnewline \midrule \midrule
   Dependent Variable: & \multicolumn{4}{c}{novelbin}\\
   Model:                              & (1)            & (2)            & (3)            & (4)\\
   \midrule
   \emph{Variables}\\
   fac\_pubBSF                         & 0.075$^{***}$  & 0.055$^{***}$  & 0.191$^{***}$  & 0.590$^{***}$\\
                                       & (0.007)        & (0.012)        & (0.019)        & (0.091)\\
   num\_author\_log                    & 0.212$^{***}$  & 0.435$^{***}$  & 0.403$^{***}$  & 0.377$^{***}$\\
                                       & (0.005)        & (0.009)        & (0.012)        & (0.054)\\
   num\_inst\_log                      & -0.004         & 0.059$^{***}$  & 0.065$^{***}$  & -0.058\\
                                       & (0.007)        & (0.011)        & (0.015)        & (0.066)\\
   num\_country\_log                   & -0.293$^{***}$ & -0.210$^{***}$ & -0.196$^{***}$ & -0.383$^{***}$\\
                                       & (0.010)        & (0.017)        & (0.024)        & (0.092)\\
   num\_reference\_log                 & 0.146$^{***}$  & 0.273$^{***}$  & 0.447$^{***}$  & 0.283$^{***}$\\
                                       & (0.003)        & (0.006)        & (0.009)        & (0.030)\\
   leadership\_global\_classallNorth   & 0.139$^{***}$  & 0.061$^{***}$  & 0.117$^{***}$  & 0.076\\
                                       & (0.009)        & (0.021)        & (0.029)        & (0.093)\\
   leadership\_global\_classallSouth   & -0.054$^{***}$ & -0.012         & 0.083$^{*}$    & -0.082\\
                                       & (0.015)        & (0.033)        & (0.046)        & (0.128)\\
   mean\_career\_age\_log              & 0.004          & 0.123$^{***}$  & 0.108$^{***}$  & 0.006\\
                                       & (0.005)        & (0.010)        & (0.014)        & (0.055)\\
   inst\_h\_index\_log                 & -0.016$^{***}$ & -0.084$^{***}$ & -0.037$^{***}$ & 0.013\\
                                       & (0.004)        & (0.007)        & (0.010)        & (0.035)\\
   source\_h\_index\_log               & -0.028$^{***}$ & -0.096$^{***}$ & -0.061$^{***}$ & 0.102$^{***}$\\
                                       & (0.002)        & (0.004)        & (0.006)        & (0.023)\\
   core\_sourceCore                    & 0.043$^{***}$  & 0.200$^{***}$  & 0.199$^{***}$  & 0.021\\
                                       & (0.013)        & (0.030)        & (0.040)        & (0.103)\\
   \midrule
   \emph{Fixed-effects}\\
   author\_id                          & Yes            & Yes            & Yes            & Yes\\
   year                                & Yes            & Yes            & Yes            & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                        & 2,236,396      & 683,985        & 337,939        & 26,000\\
   Squared Correlation                 & 0.22318        & 0.25136        & 0.23545        & 0.23578\\
   Pseudo R$^2$                        & 0.18428        & 0.20271        & 0.18867        & 0.18729\\
   BIC                                 & 3,172,825.9    & 1,120,131.1    & 621,396.7      & 63,603.5\\
   \midrule \midrule
   \multicolumn{5}{l}{\emph{IID standard-errors in parentheses}}\\
   \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup