In [4]:
library("lme4")
library("margins")
library("stargazer")
library("emmeans")
library("ggeffects")
library("broom")
library("broom.mixed")
library("MASS")
library("pscl")
library("fixest")
library("marginaleffects")
library("modelsummary")
library("glmmTMB")
library("dplyr")

In [3]:
main_path <- "/home/20250114zmz_kd/"
data <- read.csv(paste0(main_path, "UseBSForNot/MergeInsthData_1211.csv"))
dim(data)

[1] 3227892      78

In [5]:
print(names(data))

 [1] "X"
 [2] "work_id"
 [3] "fac_pub"
 [4] "year"
 [5] "paper_type"
 [6] "paper_language"
 [7] "nwbin"
 [8] "new_word_reuse_times"
 [9] "npbin"
[10] "new_phrase_reuse_times"
[11] "novelbin"
[12] "rao_stirling"
[13] "author_id"
[14] "author_position"
[15] "institution_id"
[16] "country_code"
[17] "country"
[18] "num_author_log"
[19] "num_inst_log"
[20] "num_country_log"
[21] "num_reference_log"
[22] "timescited5_log"
[23] "timescited10_log"
[24] "timescitedall_log"
[25] "ab_length_log"
[26] "leadership_global_class"
[27] "mean_career_age_log"
[28] "inst_h_index_log"
[29] "source_id"
[30] "source_h_index_log"
[31] "source_type"
[32] "core_source"
[33] "Agricultural.and.Biological.Sciences"
[34] "Arts.and.Humanities"
[35] "Biochemistry..Genetics.and.Molecular.Biology"
[36] "Business..Management.and.Accounting"
[37] "Chemical.Engineering"
[38] "Chemistry"
[39] "Computer.Science"
[40] "Decision.Sciences"
[41] "Dentistry"
[42] "Earth.and.Planetary.Sciences"
[43] "Economics..Econometrics.and.Finance"
[44] "Energy"
[45] "Engineering"
[46] "Environmental.Science"
[47] "Health.Professions"
[48] "Immunology.and.Microbiology"
[49] "Materials.Science"
[50] "Mathematics"
[51] "Medicine"
[52] "Neuroscience"
[53] "Nursing"
[54] "Pharmacology..Toxicology.and.Pharmaceutics"
[55] "Physics.and.Astronomy"
[56] "Psychology"
[57] "Social.Sciences"
[58] "Veterinary"
[59] "domain_Health.Sciences"
[60] "domain_Life.Sciences"
[61] "domain_Physical.Sciences"
[62] "domain_Social.Sciences"
[63] "Atyp_10pct_Z"
[64] "new_word"
[65] "new_phrase"
[66] "DI5"
[67] "DI10"
[68] "num_author"
[69] "num_inst"
[70] "num_country"
[71] "num_reference"
[72] "timescited5"
[73] "timescited10"
[74] "timescitedall"
[75] "source_h_index"
[76] "mean_career_age"
[77] "ab_length"
[78] "inst_h_index"

In [6]:
colSums(is.na(data))

                                           X
                                           0
                                     work_id
                                           0
                                     fac_pub
                                           0
                                        year
                                           0
                                  paper_type
                                           0
                              paper_language
                                           0
                                       nwbin
                                           0
                        new_word_reuse_times
                                           0
                                       npbin
                                           0
                      new_phrase_reuse_times
                                           0
                                    novelbin
                                           0
                                rao_stirling
                                      303430
                                   author_id
                                           0
                             author_position
                                           0
                              institution_id
                                           0
                                country_code
                                           0
                                     country
                                           0
                              num_author_log
                                           0
                                num_inst_log
                                           0
                             num_country_log
                                           0
                           num_reference_log
                                           0
                             timescited5_log
                                      107147
                            timescited10_log
                                      163886
                           timescitedall_log
                                           0
                               ab_length_log
                                           0
                     leadership_global_class
                                           0
                         mean_career_age_log
                                           0
                            inst_h_index_log
                                           6
                                   source_id
                                           0
                          source_h_index_log
                                           0
                                 source_type
                                           0
                                 core_source
                                           0
        Agricultural.and.Biological.Sciences
                                           0
                         Arts.and.Humanities
                                           0
Biochemistry..Genetics.and.Molecular.Biology
                                           0
         Business..Management.and.Accounting
                                           0
                        Chemical.Engineering
                                           0
                                   Chemistry
                                           0
                            Computer.Science
                                           0
                           Decision.Sciences
                                           0
                                   Dentistry
                                           0
                Earth.and.Planetary.Sciences
                                           0
         Economics..Econometrics.and.Finance
                                           0
                                      Energy
                                           0
                                 Engineering
                                           0
                       Environmental.Science
                                           0
                          Health.Professions
                                           0
                 Immunology.and.Microbiology
                                           0
                           Materials.Science
                                           0
                                 Mathematics
                                           0
                                    Medicine
                                           0
                                Neuroscience
                                           0
                                     Nursing
                                           0
  Pharmacology..Toxicology.and.Pharmaceutics
                                           0
                       Physics.and.Astronomy
                                           0
                                  Psychology
                                           0
                             Social.Sciences
                                           0
                                  Veterinary
                                           0
                      domain_Health.Sciences
                                           0
                        domain_Life.Sciences
                                           0
                    domain_Physical.Sciences
                                           0
                      domain_Social.Sciences
                                           0
                                Atyp_10pct_Z
                                      413497
                                    new_word
                                      363512
                                  new_phrase
                                      363512
                                         DI5
                                     1516264
                                        DI10
                                     1637246
                                  num_author
                                           0
                                    num_inst
                                           0
                                 num_country
                                           0
                               num_reference
                                           0
                                 timescited5
                                      107147
                                timescited10
                                      163886
                               timescitedall
                                           0
                              source_h_index
                                           0
                             mean_career_age
                                           0
                                   ab_length
                                           0
                                inst_h_index
                                           6

In [7]:
# 把所有无限值替换成 NA
data[sapply(data, is.infinite)] <- NA

In [8]:
data <- data[!is.na(data$Atyp_10pct_Z), ]
dim(data)
data <- data[data$num_reference >=5, ]
dim(data)

[1] 2814103      78

[1] 2760385      78

In [9]:
# data <- data[data$ab_length > 0, ]
# dim(data)
data <- data[data$year >= 1950, ]
dim(data)

[1] 2760385      78

In [10]:
# 找出所有包含无限值的行和列
inf_mask <- sapply(data, function(col) is.infinite(col))
rows_with_inf <- apply(inf_mask, 1, any)  # 哪些行至少有一个Inf
cols_with_inf <- colnames(data)[apply(inf_mask, 2, any)]  # 哪些列有Inf

# 打印包含无限值的行数和列名
cat("包含无限值的行数:", sum(rows_with_inf), "\n")
cat("包含无限值的列名:", paste(cols_with_inf, collapse = ", "), "\n")

# 查看这些行具体内容
data_filt_with_inf <- data[rows_with_inf, c(cols_with_inf), drop=FALSE]
print(data_filt_with_inf)

包含无限值的行数: 0
包含无限值的列名:
data frame with 0 columns and 0 rows

In [11]:
data$decade <- (data$year %/% 10) * 10

In [12]:
data$leadership_global_class <- factor(data$leadership_global_class)
data <- within(data, leadership_global_class <- relevel(leadership_global_class, ref = 'shared'))
data$fac_pub <- factor(data$fac_pub)
data <- within(data, fac_pub <- relevel(fac_pub, ref = 'NonBSF'))
data$core_source <- factor(data$core_source)
data <- within(data, core_source <- relevel(core_source, ref = 'NonCore'))
data$decade <- as.factor(data$decade)

In [13]:
# variable type
paper_level <- "num_author_log + num_inst_log + num_country_log + num_reference_log + leadership_global_class + mean_career_age_log + inst_h_index_log" 
journal_level <- "source_h_index_log + core_source"
disciplines <- "Arts.and.Humanities + Biochemistry..Genetics.and.Molecular.Biology + Business..Management.and.Accounting + Chemical.Engineering + 
 Chemistry + Computer.Science + Decision.Sciences + Dentistry + Earth.and.Planetary.Sciences + 
Economics..Econometrics.and.Finance + Energy + Engineering + Environmental.Science + Health.Professions + 
Immunology.and.Microbiology + Materials.Science + Mathematics + Medicine + Neuroscience + Nursing +
Pharmacology..Toxicology.and.Pharmaceutics + Physics.and.Astronomy + Psychology + Social.Sciences + Veterinary "

In [16]:
fml <- as.formula(
  paste0("novelbin ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " + decade | author_id")
)

model_total <- feglm(fml, data = data, family = binomial("logit"), vcov = "iid")
summary(model_total)

NOTES: 4 observations removed because of NA values (RHS: 4).
       17,669 fixed-effects (78,042 observations) removed because of only 0 (or only 1) outcomes.

GLM estimation, family = binomial, Dep. Var.: novelbin
Observations: 2,682,339
Fixed-effects: author_id: 61,171
Standard-errors: IID
                                              Estimate Std. Error    z value
fac_pubBSF                                    0.078407   0.006058  12.942567
num_author_log                                0.251961   0.004571  55.121331
num_inst_log                                  0.006668   0.005830   1.143847
num_country_log                              -0.281281   0.008623 -32.620194
num_reference_log                             0.146210   0.002932  49.863537
leadership_global_classallNorth               0.138223   0.008748  15.800371
leadership_global_classallSouth              -0.013734   0.013781  -0.996557
mean_career_age_log                           0.021688   0.004796   4.521938
inst_h_index_log                             -0.022841   0.003707  -6.161047
source_h_index_log                           -0.041600   0.002180 -19.086730
core_sourceCore                               0.087523   0.011975   7.308529
Arts.and.Humanities                           0.569149   0.028355  20.072221
Biochemistry..Genetics.and.Molecular.Biology  0.498699   0.005493  90.791645
Business..Management.and.Accounting           0.058639   0.036093   1.624641
Chemical.Engineering                          0.063859   0.007818   8.168373
Chemistry                                     0.084154   0.004837  17.396632
Computer.Science                              0.415060   0.011265  36.843995
Decision.Sciences                             0.470991   0.030209  15.591308
Dentistry                                     0.683457   0.030852  22.152782
Earth.and.Planetary.Sciences                  0.204868   0.007744  26.454354
Economics..Econometrics.and.Finance           0.347874   0.034211  10.168399
Energy                                        0.080839   0.007870  10.272091
Engineering                                   0.195234   0.004249  45.945768
Environmental.Science                         0.452609   0.007011  64.558945
Health.Professions                            0.344179   0.025101  13.711633
Immunology.and.Microbiology                   0.242444   0.011629  20.848076
Materials.Science                             0.033939   0.004195   8.090510
Mathematics                                   0.195661   0.022654   8.636984
Medicine                                      0.605418   0.006006 100.809971
Neuroscience                                  0.434957   0.011112  39.142210
Nursing                                       0.602399   0.016985  35.465570
Pharmacology..Toxicology.and.Pharmaceutics    0.290408   0.015338  18.933324
Physics.and.Astronomy                        -0.118208   0.005236 -22.576616
Psychology                                    0.171673   0.028042   6.122115
Social.Sciences                               0.342242   0.025021  13.678025
Veterinary                                    0.586541   0.048289  12.146585
decade1960                                   -0.081156   0.076764  -1.057217
decade1970                                   -0.177319   0.073399  -2.415816
decade1980                                   -0.129044   0.072805  -1.772462
decade1990                                    0.126047   0.072724   1.733234
decade2000                                   -0.070584   0.072805  -0.969498
decade2010                                   -0.185746   0.072948  -2.546267
decade2020                                   -0.175307   0.073121  -2.397511
                                               Pr(>|z|)
fac_pubBSF                                    < 2.2e-16 ***
num_author_log                                < 2.2e-16 ***
num_inst_log                                 2.5269e-01
num_country_log                               < 2.2e-16 ***
num_reference_log                             < 2.2e-16 ***
leadership_global_classallNorth               < 2.2e-16 ***
leadership_global_classallSouth              3.1898e-01
mean_career_age_log                          6.1276e-06 ***
inst_h_index_log                             7.2265e-10 ***
source_h_index_log                            < 2.2e-16 ***
core_sourceCore                              2.7008e-13 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.0424e-01
Chemical.Engineering                         3.1258e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                             < 2.2e-16 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                            5.9416e-16 ***
Mathematics                                   < 2.2e-16 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                   9.2341e-10 ***
Social.Sciences                               < 2.2e-16 ***
Veterinary                                    < 2.2e-16 ***
decade1960                                   2.9041e-01
decade1970                                   1.5700e-02 *
decade1980                                   7.6318e-02 .
decade1990                                   8.3054e-02 .
decade2000                                   3.3230e-01
decade2010                                   1.0888e-02 *
decade2020                                   1.6507e-02 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Log-Likelihood: -1,434,850.5   Adj. Pseudo R2: 0.150464
           BIC:  3,775,802.8     Squared Cor.: 0.225754

In [17]:
# 每组 reg_class 的平均预测概率
res_year <- avg_comparisons(model_total, variables = "fac_pub", by = 'year', comparison = "ratio")
res_year

   term    contrast                 year estimate std.error   statistic p.value
1  fac_pub mean(BSF) / mean(NonBSF) 1950 1.043906 0.003489774 299.1327  0
2  fac_pub mean(BSF) / mean(NonBSF) 1951 1.043812 0.003475804 300.3082  0
3  fac_pub mean(BSF) / mean(NonBSF) 1952 1.042042 0.003334492 312.5041  0
4  fac_pub mean(BSF) / mean(NonBSF) 1953 1.041591 0.003297087 315.9124  0
5  fac_pub mean(BSF) / mean(NonBSF) 1954 1.044018 0.003488701 299.2570  0
6  fac_pub mean(BSF) / mean(NonBSF) 1955 1.042944 0.003407367 306.0851  0
7  fac_pub mean(BSF) / mean(NonBSF) 1956 1.047888 0.003803191 275.5286  0
8  fac_pub mean(BSF) / mean(NonBSF) 1957 1.048483 0.003851646 272.2169  0
9  fac_pub mean(BSF) / mean(NonBSF) 1958 1.044585 0.003533643 295.6114  0
10 fac_pub mean(BSF) / mean(NonBSF) 1959 1.045884 0.003645026 286.9345  0
11 fac_pub mean(BSF) / mean(NonBSF) 1960 1.047419 0.003908045 268.0160  0
12 fac_pub mean(BSF) / mean(NonBSF) 1961 1.046359 0.003839022 272.5587  0
13 fac_pub mean(BSF) / mean(NonBSF) 1962 1.047709 0.003936293 266.1664  0
14 fac_pub mean(BSF) / mean(NonBSF) 1963 1.044025 0.003627316 287.8230  0
15 fac_pub mean(BSF) / mean(NonBSF) 1964 1.046839 0.003858100 271.3353  0
16 fac_pub mean(BSF) / mean(NonBSF) 1965 1.046239 0.003812731 274.4066  0
17 fac_pub mean(BSF) / mean(NonBSF) 1966 1.046129 0.003810595 274.5317  0
18 fac_pub mean(BSF) / mean(NonBSF) 1967 1.047197 0.003897741 268.6676  0
19 fac_pub mean(BSF) / mean(NonBSF) 1968 1.047845 0.003947532 265.4431  0
20 fac_pub mean(BSF) / mean(NonBSF) 1969 1.046954 0.003873911 270.2575  0
21 fac_pub mean(BSF) / mean(NonBSF) 1970 1.047600 0.003910430 267.8989  0
22 fac_pub mean(BSF) / mean(NonBSF) 1971 1.048183 0.003952197 265.2151  0
23 fac_pub mean(BSF) / mean(NonBSF) 1972 1.047356 0.003895933 268.8331  0
24 fac_pub mean(BSF) / mean(NonBSF) 1973 1.046665 0.003830380 273.2535  0
25 fac_pub mean(BSF) / mean(NonBSF) 1974 1.047256 0.003883182 269.6902  0
26 fac_pub mean(BSF) / mean(NonBSF) 1975 1.047135 0.003878406 269.9911  0
27 fac_pub mean(BSF) / mean(NonBSF) 1976 1.047043 0.003865646 270.8584  0
28 fac_pub mean(BSF) / mean(NonBSF) 1977 1.047054 0.003869047 270.6233  0
29 fac_pub mean(BSF) / mean(NonBSF) 1978 1.047537 0.003895708 268.8951  0
30 fac_pub mean(BSF) / mean(NonBSF) 1979 1.046037 0.003779048 276.7990  0
⋮  ⋮       ⋮                        ⋮    ⋮        ⋮           ⋮         ⋮
47 fac_pub mean(BSF) / mean(NonBSF) 1996 1.039485 0.003272424 317.6500  0
48 fac_pub mean(BSF) / mean(NonBSF) 1997 1.039243 0.003254959 319.2798  0
49 fac_pub mean(BSF) / mean(NonBSF) 1998 1.038861 0.003221464 322.4810  0
50 fac_pub mean(BSF) / mean(NonBSF) 1999 1.038801 0.003218969 322.7123  0
51 fac_pub mean(BSF) / mean(NonBSF) 2000 1.041321 0.003413950 305.0193  0
52 fac_pub mean(BSF) / mean(NonBSF) 2001 1.041066 0.003391889 306.9281  0
53 fac_pub mean(BSF) / mean(NonBSF) 2002 1.040788 0.003370874 308.7591  0
54 fac_pub mean(BSF) / mean(NonBSF) 2003 1.040175 0.003321481 313.1661  0
55 fac_pub mean(BSF) / mean(NonBSF) 2004 1.039836 0.003294350 315.6423  0
56 fac_pub mean(BSF) / mean(NonBSF) 2005 1.039359 0.003256513 319.1633  0
57 fac_pub mean(BSF) / mean(NonBSF) 2006 1.039225 0.003242017 320.5488  0
58 fac_pub mean(BSF) / mean(NonBSF) 2007 1.038770 0.003205868 324.0213  0
59 fac_pub mean(BSF) / mean(NonBSF) 2008 1.038350 0.003171729 327.3765  0
60 fac_pub mean(BSF) / mean(NonBSF) 2009 1.038266 0.003164289 328.1198  0
61 fac_pub mean(BSF) / mean(NonBSF) 2010 1.039241 0.003237509 321.0004  0
62 fac_pub mean(BSF) / mean(NonBSF) 2011 1.039160 0.003230502 321.6715  0
63 fac_pub mean(BSF) / mean(NonBSF) 2012 1.038977 0.003213832 323.2831  0
64 fac_pub mean(BSF) / mean(NonBSF) 2013 1.038839 0.003201522 324.4830  0
65 fac_pub mean(BSF) / mean(NonBSF) 2014 1.038714 0.003189996 325.6161  0
66 fac_pub mean(BSF) / mean(NonBSF) 2015 1.038407 0.003165510 328.0377  0
67 fac_pub mean(BSF) / mean(NonBSF) 2016 1.038271 0.003154054 329.1861  0
68 fac_pub mean(BSF) / mean(NonBSF) 2017 1.038190 0.003147262 329.8709  0
69 fac_pub mean(BSF) / mean(NonBSF) 2018 1.037920 0.003125539 332.0772  0
70 fac_pub mean(BSF) / mean(NonBSF) 2019 1.037910 0.003123682 332.2713  0
71 fac_pub mean(BSF) / mean(NonBSF) 2020 1.037378 0.003080803 336.7234  0
72 fac_pub mean(BSF) / mean(NonBSF) 2021 1.037174 0.003067246 338.1451  0
73 fac_pub mean(BSF) / mean(NonBSF) 2022 1.037132 0.003061298 338.7883  0
74 fac_pub mean(BSF) / mean(NonBSF) 2023 1.037360 0.003078982 336.9165  0
75 fac_pub mean(BSF) / mean(NonBSF) 2024 1.036987 0.003048478 340.1656  0
76 fac_pub mean(BSF) / mean(NonBSF) 2025 1.036421 0.003153186 328.6901  0
   s.value conf.low conf.high predicted_lo predicted_hi predicted
1  Inf     1.037066 1.050746  0.24952031   0.26448921   0.24952031
2  Inf     1.037000 1.050625  0.51321315   0.53277105   0.51321315
3  Inf     1.035507 1.048578  0.32625672   0.34372069   0.32625672
4  Inf     1.035128 1.048053  0.10596614   0.11362702   0.10596614
5  Inf     1.037180 1.050856  0.19954549   0.21236472   0.19954549
6  Inf     1.036266 1.049623  0.60607177   0.62462763   0.60607177
7  Inf     1.040434 1.055342  0.29326446   0.30977439   0.29326446
8  Inf     1.040934 1.056032  0.46714847   0.48670608   0.46714847
9  Inf     1.037659 1.051511  0.27392965   0.28979742   0.27392965
10 Inf     1.038740 1.053028  0.18353382   0.19557574   0.18353382
11 Inf     1.039759 1.055078  0.65534764   0.67283534   0.65534764
12 Inf     1.038835 1.053883  0.28589659   0.30216907   0.28589659
13 Inf     1.039994 1.055424  0.08742685   0.09388817   0.08742685
14 Inf     1.036916 1.051134  0.15775724   0.16845687   0.15775724
15 Inf     1.039277 1.054400  0.08647084   0.09286870   0.08647084
16 Inf     1.038766 1.053712  0.07406179   0.07962154   0.07406179
17 Inf     1.038660 1.053598  0.70077226   0.71695060   0.70077226
18 Inf     1.039557 1.054836  0.40022635   0.41918630   0.40022635
19 Inf     1.040108 1.055582  0.46462210   0.48417005   0.46462210
20 Inf     1.039361 1.054546  0.36747136   0.38587793   0.36747136
21 Inf     1.039936 1.055264  0.08898660   0.09555113   0.08898660
22 Inf     1.040436 1.055929  0.16245732   0.17341009   0.16245732
23 Inf     1.039720 1.054992  0.21561204   0.22916791   0.21561204
24 Inf     1.039157 1.054172  0.21978875   0.23352904   0.21978875
25 Inf     1.039645 1.054867  0.09033605   0.09698953   0.09033605
26 Inf     1.039534 1.054737  0.14236986   0.15221448   0.14236986
27 Inf     1.039466 1.054619  0.64273638   0.66053252   0.64273638
28 Inf     1.039471 1.054638  0.12616615   0.13506676   0.12616615
29 Inf     1.039902 1.055172  0.30735197   0.32429107   0.30735197
30 Inf     1.038630 1.053444  0.08752664   0.09399458   0.08752664
⋮  ⋮       ⋮        ⋮         ⋮            ⋮            ⋮
47 Inf     1.033072 1.045899  0.75529466   0.76949477   0.75529466
48 Inf     1.032863 1.045622  0.17712500   0.18884369   0.17712500
49 Inf     1.032547 1.045175  0.50817072   0.52774479   0.50817072
50 Inf     1.032492 1.045110  0.39881509   0.41775475   0.39881509
51 Inf     1.034629 1.048012  0.17907670   0.19089456   0.17907670
52 Inf     1.034418 1.047714  0.21795977   0.23161966   0.23161966
53 Inf     1.034181 1.047395  0.33325062   0.35089398   0.33325062
54 Inf     1.033665 1.046685  0.49717045   0.51676600   0.51676600
55 Inf     1.033380 1.046293  0.77241497   0.78590322   0.77241497
56 Inf     1.032977 1.045742  0.27148500   0.28726719   0.27148500
57 Inf     1.032870 1.045579  0.87831243   0.88644713   0.87831243
58 Inf     1.032486 1.045053  0.37838067   0.39699073   0.37838067
59 Inf     1.032133 1.044566  0.86182246   0.87089748   0.86182246
60 Inf     1.032064 1.044468  0.09080406   0.09748832   0.09080406
61 Inf     1.032896 1.045587  0.83089641   0.84162929   0.83089641
62 Inf     1.032829 1.045492  0.17116482   0.18257668   0.17116482
63 Inf     1.032678 1.045276  0.15695404   0.16761003   0.15695404
64 Inf     1.032565 1.045114  0.13624076   0.14573357   0.14573357
65 Inf     1.032462 1.044966  0.28896528   0.30533775   0.28896528
66 Inf     1.032203 1.044611  0.16239634   0.17334585   0.16239634
67 Inf     1.032089 1.044453  0.28360953   0.29980649   0.28360953
68 Inf     1.032022 1.044359  0.10842148   0.11623678   0.10842148
69 Inf     1.031794 1.044046  0.22822466   0.24232853   0.24232853
70 Inf     1.031788 1.044032  0.30643167   0.32334372   0.30643167
71 Inf     1.031340 1.043417  0.10664565   0.11434936   0.10664565
72 Inf     1.031163 1.043186  0.54564468   0.56500400   0.54564468
73 Inf     1.031132 1.043132  0.25704474   0.27230125   0.25704474
74 Inf     1.031325 1.043394  0.29312086   0.30962625   0.29312086
75 Inf     1.031012 1.042962  0.28176167   0.29789698   0.28176167
76 Inf     1.030241 1.042601  0.45303758   0.47252831   0.45303758

In [15]:
MEs = ggemmeans(model_total, terms=c('fac_pub', 'decade'), typical='median')

In [15]:
MEs

   x      predicted std.error  conf.low  conf.high group
1  NonBSF 0.2891848 0.03128525 0.2767451 0.3019501 1950
2  NonBSF 0.2727920 0.08242563 0.2419434 0.3059862 1960
3  NonBSF 0.2541376 0.07898041 0.2259253 0.2845777 1970
4  NonBSF 0.2633962 0.07806457 0.2348015 0.2941346 1980
5  NonBSF 0.3157658 0.07768517 0.2838265 0.3495452 1990
6  NonBSF 0.2748942 0.07748536 0.2456776 0.3061751 2000
7  NonBSF 0.2525434 0.07739032 0.2249978 0.2822332 2010
8  NonBSF 0.2545190 0.07742528 0.2268113 0.2843667 2020
9  BSF    0.3055643 0.03130841 0.2927009 0.3187384 1950
10 BSF    0.2886201 0.08244415 0.2566062 0.3228931 1960
11 BSF    0.2692841 0.07899701 0.2399253 0.3008136 1970
12 BSF    0.2788882 0.07808282 0.2491739 0.3106796 1980
13 BSF    0.3329458 0.07770867 0.3000210 0.3675863 1990
14 BSF    0.2907955 0.07749545 0.2604922 0.3230839 2000
15 BSF    0.2676290 0.07738580 0.2389656 0.2983825 2010
16 BSF    0.2696800 0.07742352 0.2408557 0.3005880 2020

In [18]:
fname = paste0(main_path, "UseBSForNot/compare_ns_1211_year.csv")
write.csv(res_year, fname, row.names = FALSE)