In [2]:
library("lme4")
library("margins")
library("stargazer")
library("emmeans")
library("ggeffects")
library("broom")
library("broom.mixed")
library("MASS")
library("pscl")
library("fixest")
library("marginaleffects")
library("modelsummary")
library("glmmTMB")
library("dplyr")

In [3]:
main_path <- "/home/20250114zmz_kd/"
data <- read.csv(paste0(main_path, "UseBSForNot/MergeInsthData_1211.csv"))
dim(data)

[1] 3227892      78

In [4]:
print(names(data))

 [1] "X"
 [2] "work_id"
 [3] "fac_pub"
 [4] "year"
 [5] "paper_type"
 [6] "paper_language"
 [7] "nwbin"
 [8] "new_word_reuse_times"
 [9] "npbin"
[10] "new_phrase_reuse_times"
[11] "novelbin"
[12] "rao_stirling"
[13] "author_id"
[14] "author_position"
[15] "institution_id"
[16] "country_code"
[17] "country"
[18] "num_author_log"
[19] "num_inst_log"
[20] "num_country_log"
[21] "num_reference_log"
[22] "timescited5_log"
[23] "timescited10_log"
[24] "timescitedall_log"
[25] "ab_length_log"
[26] "leadership_global_class"
[27] "mean_career_age_log"
[28] "inst_h_index_log"
[29] "source_id"
[30] "source_h_index_log"
[31] "source_type"
[32] "core_source"
[33] "Agricultural.and.Biological.Sciences"
[34] "Arts.and.Humanities"
[35] "Biochemistry..Genetics.and.Molecular.Biology"
[36] "Business..Management.and.Accounting"
[37] "Chemical.Engineering"
[38] "Chemistry"
[39] "Computer.Science"
[40] "Decision.Sciences"
[41] "Dentistry"
[42] "Earth.and.Planetary.Sciences"
[43] "Economics..Econometrics.and.Finance"
[44] "Energy"
[45] "Engineering"
[46] "Environmental.Science"
[47] "Health.Professions"
[48] "Immunology.and.Microbiology"
[49] "Materials.Science"
[50] "Mathematics"
[51] "Medicine"
[52] "Neuroscience"
[53] "Nursing"
[54] "Pharmacology..Toxicology.and.Pharmaceutics"
[55] "Physics.and.Astronomy"
[56] "Psychology"
[57] "Social.Sciences"
[58] "Veterinary"
[59] "domain_Health.Sciences"
[60] "domain_Life.Sciences"
[61] "domain_Physical.Sciences"
[62] "domain_Social.Sciences"
[63] "Atyp_10pct_Z"
[64] "new_word"
[65] "new_phrase"
[66] "DI5"
[67] "DI10"
[68] "num_author"
[69] "num_inst"
[70] "num_country"
[71] "num_reference"
[72] "timescited5"
[73] "timescited10"
[74] "timescitedall"
[75] "source_h_index"
[76] "mean_career_age"
[77] "ab_length"
[78] "inst_h_index"

In [5]:
colSums(is.na(data))

                                           X
                                           0
                                     work_id
                                           0
                                     fac_pub
                                           0
                                        year
                                           0
                                  paper_type
                                           0
                              paper_language
                                           0
                                       nwbin
                                           0
                        new_word_reuse_times
                                           0
                                       npbin
                                           0
                      new_phrase_reuse_times
                                           0
                                    novelbin
                                           0
                                rao_stirling
                                      303430
                                   author_id
                                           0
                             author_position
                                           0
                              institution_id
                                           0
                                country_code
                                           0
                                     country
                                           0
                              num_author_log
                                           0
                                num_inst_log
                                           0
                             num_country_log
                                           0
                           num_reference_log
                                           0
                             timescited5_log
                                      107147
                            timescited10_log
                                      163886
                           timescitedall_log
                                           0
                               ab_length_log
                                           0
                     leadership_global_class
                                           0
                         mean_career_age_log
                                           0
                            inst_h_index_log
                                           6
                                   source_id
                                           0
                          source_h_index_log
                                           0
                                 source_type
                                           0
                                 core_source
                                           0
        Agricultural.and.Biological.Sciences
                                           0
                         Arts.and.Humanities
                                           0
Biochemistry..Genetics.and.Molecular.Biology
                                           0
         Business..Management.and.Accounting
                                           0
                        Chemical.Engineering
                                           0
                                   Chemistry
                                           0
                            Computer.Science
                                           0
                           Decision.Sciences
                                           0
                                   Dentistry
                                           0
                Earth.and.Planetary.Sciences
                                           0
         Economics..Econometrics.and.Finance
                                           0
                                      Energy
                                           0
                                 Engineering
                                           0
                       Environmental.Science
                                           0
                          Health.Professions
                                           0
                 Immunology.and.Microbiology
                                           0
                           Materials.Science
                                           0
                                 Mathematics
                                           0
                                    Medicine
                                           0
                                Neuroscience
                                           0
                                     Nursing
                                           0
  Pharmacology..Toxicology.and.Pharmaceutics
                                           0
                       Physics.and.Astronomy
                                           0
                                  Psychology
                                           0
                             Social.Sciences
                                           0
                                  Veterinary
                                           0
                      domain_Health.Sciences
                                           0
                        domain_Life.Sciences
                                           0
                    domain_Physical.Sciences
                                           0
                      domain_Social.Sciences
                                           0
                                Atyp_10pct_Z
                                      413497
                                    new_word
                                      363512
                                  new_phrase
                                      363512
                                         DI5
                                     1516264
                                        DI10
                                     1637246
                                  num_author
                                           0
                                    num_inst
                                           0
                                 num_country
                                           0
                               num_reference
                                           0
                                 timescited5
                                      107147
                                timescited10
                                      163886
                               timescitedall
                                           0
                              source_h_index
                                           0
                             mean_career_age
                                           0
                                   ab_length
                                           0
                                inst_h_index
                                           6

In [6]:
# 把所有无限值替换成 NA
data[sapply(data, is.infinite)] <- NA

In [7]:
# data <- data[!is.na(data$Atyp_10pct_Z), ]
# dim(data)
data <- data[data$num_reference >=5, ]
dim(data)

[1] 2768162      78

In [8]:
# data <- data[data$ab_length > 0, ]
# dim(data)
data <- data[data$year >= 1950, ]
dim(data)

[1] 2768162      78

In [9]:
# 找出所有包含无限值的行和列
inf_mask <- sapply(data, function(col) is.infinite(col))
rows_with_inf <- apply(inf_mask, 1, any)  # 哪些行至少有一个Inf
cols_with_inf <- colnames(data)[apply(inf_mask, 2, any)]  # 哪些列有Inf

# 打印包含无限值的行数和列名
cat("包含无限值的行数:", sum(rows_with_inf), "\n")
cat("包含无限值的列名:", paste(cols_with_inf, collapse = ", "), "\n")

# 查看这些行具体内容
data_filt_with_inf <- data[rows_with_inf, c(cols_with_inf), drop=FALSE]
print(data_filt_with_inf)

包含无限值的行数: 0
包含无限值的列名:
data frame with 0 columns and 0 rows

In [10]:
data$leadership_global_class <- factor(data$leadership_global_class)
data <- within(data, leadership_global_class <- relevel(leadership_global_class, ref = 'shared'))
data$fac_pub <- factor(data$fac_pub)
data <- within(data, fac_pub <- relevel(fac_pub, ref = 'NonBSF'))
data$core_source <- factor(data$core_source)
data <- within(data, core_source <- relevel(core_source, ref = 'NonCore'))
data$year <- as.factor(data$year)

In [11]:
# variable type
paper_level <- "num_author_log + num_inst_log + num_country_log + num_reference_log + leadership_global_class + mean_career_age_log + inst_h_index_log" 
journal_level <- "source_h_index_log + core_source"
disciplines <- "Arts.and.Humanities + Biochemistry..Genetics.and.Molecular.Biology + Business..Management.and.Accounting + Chemical.Engineering + 
 Chemistry + Computer.Science + Decision.Sciences + Dentistry + Earth.and.Planetary.Sciences + 
Economics..Econometrics.and.Finance + Energy + Engineering + Environmental.Science + Health.Professions + 
Immunology.and.Microbiology + Materials.Science + Mathematics + Medicine + Neuroscience + Nursing +
Pharmacology..Toxicology.and.Pharmaceutics + Physics.and.Astronomy + Psychology + Social.Sciences + Veterinary "

In [12]:
fml <- as.formula(
  paste0("rao_stirling ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_ps <- feols(fml, data = data[(data$domain_Physical.Sciences == 1), ], vcov = "iid")
summary(model_ps)

NOTE: 3 observations removed because of NA values (RHS: 3).

OLS estimation, Dep. Var.: rao_stirling
Observations: 2,321,151
Fixed-effects: author_id: 75,686,  year: 76
Standard-errors: IID
                                              Estimate Std. Error    t value
fac_pubBSF                                   -0.000475   0.000083  -5.748206
num_author_log                               -0.000074   0.000064  -1.153360
num_inst_log                                  0.000826   0.000082  10.031007
num_country_log                              -0.003177   0.000120 -26.557616
num_reference_log                             0.002499   0.000041  61.403041
leadership_global_classallNorth               0.001470   0.000118  12.493404
leadership_global_classallSouth               0.000677   0.000187   3.627642
mean_career_age_log                           0.000533   0.000068   7.876568
inst_h_index_log                             -0.000269   0.000052  -5.147862
source_h_index_log                           -0.001061   0.000031 -34.764285
core_sourceCore                              -0.000018   0.000160  -0.113345
Arts.and.Humanities                           0.045681   0.000423 107.940277
Biochemistry..Genetics.and.Molecular.Biology  0.021180   0.000089 237.554682
Business..Management.and.Accounting           0.150058   0.000533 281.480240
Chemical.Engineering                         -0.003369   0.000104 -32.411912
Chemistry                                     0.002967   0.000068  43.542715
Computer.Science                              0.029174   0.000152 192.027881
Decision.Sciences                             0.031987   0.000452  70.696276
Dentistry                                     0.055820   0.000538 103.768732
Earth.and.Planetary.Sciences                  0.007982   0.000103  77.711097
Economics..Econometrics.and.Finance           0.070898   0.000578 122.738774
Energy                                       -0.005759   0.000104 -55.478343
Engineering                                   0.003594   0.000057  62.576554
Environmental.Science                         0.010409   0.000102 102.131673
Health.Professions                            0.047172   0.000497  94.863317
Immunology.and.Microbiology                   0.003849   0.000375  10.259208
Materials.Science                            -0.001089   0.000056 -19.279340
Mathematics                                   0.030956   0.000296 104.671417
Medicine                                      0.027532   0.000112 245.782239
Neuroscience                                  0.034889   0.000231 151.176980
Nursing                                       0.011133   0.000364  30.573313
Pharmacology..Toxicology.and.Pharmaceutics    0.006566   0.000255  25.716921
Physics.and.Astronomy                        -0.000700   0.000070 -10.059586
Psychology                                    0.042208   0.000723  58.377847
Social.Sciences                               0.050985   0.000461 110.633985
Veterinary                                    0.009732   0.001347   7.224213
                                               Pr(>|t|)
fac_pubBSF                                   9.0207e-09 ***
num_author_log                               2.4876e-01
num_inst_log                                  < 2.2e-16 ***
num_country_log                               < 2.2e-16 ***
num_reference_log                             < 2.2e-16 ***
leadership_global_classallNorth               < 2.2e-16 ***
leadership_global_classallSouth              2.8603e-04 ***
mean_career_age_log                          3.3665e-15 ***
inst_h_index_log                             2.6349e-07 ***
source_h_index_log                            < 2.2e-16 ***
core_sourceCore                              9.0976e-01
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                             < 2.2e-16 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                   < 2.2e-16 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                       < 2.2e-16 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                    < 2.2e-16 ***
Social.Sciences                               < 2.2e-16 ***
Veterinary                                   5.0417e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.030044     Adj. R2: 0.547743
                 Within R2: 0.139831

In [13]:
MEs = ggemmeans(model_ps, terms=c('fac_pub'), typical='median')

In [14]:
MEs

  x      predicted std.error    conf.low  conf.high group
1 NonBSF 0.1368185 0.0004391578 0.1359577 0.1376792 1
2 BSF    0.1363430 0.0004391761 0.1354822 0.1372037 1

In [15]:
fname = paste0(main_path, "UseBSForNot/predict_rao_1211_ps.csv")
write.csv(MEs, fname, row.names = FALSE)

In [16]:
fml <- as.formula(
  paste0("rao_stirling ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_ls <- feols(fml, data = data[(data$domain_Life.Sciences == 1), ], vcov = "iid")
summary(model_ls)

OLS estimation, Dep. Var.: rao_stirling
Observations: 729,686
Fixed-effects: author_id: 43,960,  year: 75
Standard-errors: IID
                                                Estimate Std. Error    t value
fac_pubBSF                                    0.01378190   0.000154  89.356033
num_author_log                                0.00112469   0.000112   9.999113
num_inst_log                                  0.00199448   0.000145  13.780334
num_country_log                              -0.00107485   0.000219  -4.915430
num_reference_log                             0.00235265   0.000078  30.133047
leadership_global_classallNorth               0.00137342   0.000269   5.112106
leadership_global_classallSouth              -0.00004073   0.000425  -0.095770
mean_career_age_log                           0.00152598   0.000121  12.614467
inst_h_index_log                              0.00049775   0.000096   5.178392
source_h_index_log                           -0.00000459   0.000054  -0.084858
core_sourceCore                               0.00010162   0.000392   0.258981
Arts.and.Humanities                           0.04791098   0.001305  36.720274
Biochemistry..Genetics.and.Molecular.Biology  0.00161984   0.000129  12.544956
Business..Management.and.Accounting           0.04163092   0.001929  21.585447
Chemical.Engineering                          0.00710819   0.000495  14.368936
Chemistry                                     0.00678247   0.000130  52.055282
Computer.Science                              0.02756808   0.000329  83.684288
Decision.Sciences                             0.05213024   0.001566  33.296917
Dentistry                                     0.00943467   0.000890  10.605737
Earth.and.Planetary.Sciences                  0.01605656   0.000396  40.537296
Economics..Econometrics.and.Finance           0.05808722   0.001978  29.359562
Energy                                        0.01830291   0.000380  48.113855
Engineering                                   0.01432987   0.000155  92.179128
Environmental.Science                         0.01182683   0.000168  70.386971
Health.Professions                            0.01957222   0.000892  21.941840
Immunology.and.Microbiology                  -0.00620525   0.000168 -36.891998
Materials.Science                             0.01154146   0.000130  88.609913
Mathematics                                   0.04554534   0.001106  41.163925
Medicine                                     -0.00100296   0.000104  -9.679586
Neuroscience                                  0.00400595   0.000175  22.882582
Nursing                                      -0.00091078   0.000276  -3.302731
Pharmacology..Toxicology.and.Pharmaceutics   -0.00072900   0.000231  -3.149408
Physics.and.Astronomy                         0.01678659   0.000217  77.291947
Psychology                                    0.02821348   0.000598  47.176793
Social.Sciences                               0.05071813   0.000938  54.059950
Veterinary                                    0.00102417   0.000818   1.251556
                                               Pr(>|t|)
fac_pubBSF                                    < 2.2e-16 ***
num_author_log                                < 2.2e-16 ***
num_inst_log                                  < 2.2e-16 ***
num_country_log                              8.8608e-07 ***
num_reference_log                             < 2.2e-16 ***
leadership_global_classallNorth              3.1867e-07 ***
leadership_global_classallSouth              9.2370e-01
mean_career_age_log                           < 2.2e-16 ***
inst_h_index_log                             2.2387e-07 ***
source_h_index_log                           9.3237e-01
core_sourceCore                              7.9565e-01
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                             < 2.2e-16 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                   < 2.2e-16 ***
Medicine                                      < 2.2e-16 ***
Neuroscience                                  < 2.2e-16 ***
Nursing                                      9.5753e-04 ***
Pharmacology..Toxicology.and.Pharmaceutics   1.6361e-03 **
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                    < 2.2e-16 ***
Social.Sciences                               < 2.2e-16 ***
Veterinary                                   2.1073e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.02995     Adj. R2: 0.558965
                Within R2: 0.07881

In [17]:
MEs = ggemmeans(model_ls, terms=c('fac_pub'), typical='median')
MEs

  x      predicted std.error    conf.low  conf.high group
1 NonBSF 0.1480510 0.0008399310 0.1464047 0.1496972 1
2 BSF    0.1618329 0.0008412773 0.1601840 0.1634817 1

In [18]:
fname = paste0(main_path, "UseBSForNot/predict_rao_1211_ls.csv")
write.csv(MEs, fname, row.names = FALSE)

In [19]:
fml <- as.formula(
  paste0("rao_stirling ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_hs <- feols(fml, data = data[(data$domain_Health.Sciences == 1), ], vcov = "iid")
summary(model_hs)

NOTE: 2 observations removed because of NA values (LHS: 1, RHS: 1).

OLS estimation, Dep. Var.: rao_stirling
Observations: 376,452
Fixed-effects: author_id: 35,489,  year: 75
Standard-errors: IID
                                              Estimate Std. Error    t value
fac_pubBSF                                    0.018903   0.000255  74.270804
num_author_log                               -0.000162   0.000170  -0.954099
num_inst_log                                  0.002437   0.000211  11.526151
num_country_log                               0.000129   0.000326   0.395635
num_reference_log                             0.002476   0.000121  20.544861
leadership_global_classallNorth               0.000424   0.000410   1.034254
leadership_global_classallSouth               0.000508   0.000634   0.800892
mean_career_age_log                          -0.000011   0.000194  -0.058531
inst_h_index_log                              0.002095   0.000142  14.774501
source_h_index_log                            0.000738   0.000085   8.714286
core_sourceCore                               0.002267   0.000559   4.055599
Arts.and.Humanities                           0.042142   0.001557  27.067095
Biochemistry..Genetics.and.Molecular.Biology  0.002673   0.000156  17.096865
Business..Management.and.Accounting           0.034760   0.002253  15.429875
Chemical.Engineering                          0.011406   0.001067  10.685339
Chemistry                                     0.012097   0.000237  51.134408
Computer.Science                              0.031053   0.000502  61.827337
Decision.Sciences                             0.041290   0.002049  20.153823
Dentistry                                     0.020568   0.000579  35.519059
Earth.and.Planetary.Sciences                  0.023057   0.001107  20.827451
Economics..Econometrics.and.Finance           0.041635   0.001450  28.717285
Energy                                        0.015681   0.000762  20.567743
Engineering                                   0.025461   0.000264  96.348003
Environmental.Science                         0.017258   0.000354  48.812282
Health.Professions                            0.020659   0.000486  42.490438
Immunology.and.Microbiology                  -0.005568   0.000239 -23.260284
Materials.Science                             0.016459   0.000250  65.903208
Mathematics                                   0.037559   0.001191  31.528636
Medicine                                      0.002444   0.000387   6.322550
Neuroscience                                  0.001960   0.000305   6.415776
Nursing                                       0.002182   0.000376   5.809057
Pharmacology..Toxicology.and.Pharmaceutics    0.005259   0.000431  12.214926
Physics.and.Astronomy                         0.029365   0.000438  67.103100
Psychology                                    0.029934   0.000754  39.698691
Social.Sciences                               0.037664   0.000891  42.287252
Veterinary                                    0.003255   0.000786   4.140114
                                               Pr(>|t|)
fac_pubBSF                                    < 2.2e-16 ***
num_author_log                               3.4003e-01
num_inst_log                                  < 2.2e-16 ***
num_country_log                              6.9237e-01
num_reference_log                             < 2.2e-16 ***
leadership_global_classallNorth              3.0102e-01
leadership_global_classallSouth              4.2319e-01
mean_career_age_log                          9.5333e-01
inst_h_index_log                              < 2.2e-16 ***
source_h_index_log                            < 2.2e-16 ***
core_sourceCore                              5.0017e-05 ***
Arts.and.Humanities                           < 2.2e-16 ***
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting           < 2.2e-16 ***
Chemical.Engineering                          < 2.2e-16 ***
Chemistry                                     < 2.2e-16 ***
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                             < 2.2e-16 ***
Dentistry                                     < 2.2e-16 ***
Earth.and.Planetary.Sciences                  < 2.2e-16 ***
Economics..Econometrics.and.Finance           < 2.2e-16 ***
Energy                                        < 2.2e-16 ***
Engineering                                   < 2.2e-16 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                            < 2.2e-16 ***
Immunology.and.Microbiology                   < 2.2e-16 ***
Materials.Science                             < 2.2e-16 ***
Mathematics                                   < 2.2e-16 ***
Medicine                                     2.5760e-10 ***
Neuroscience                                 1.4029e-10 ***
Nursing                                      6.2881e-09 ***
Pharmacology..Toxicology.and.Pharmaceutics    < 2.2e-16 ***
Physics.and.Astronomy                         < 2.2e-16 ***
Psychology                                    < 2.2e-16 ***
Social.Sciences                               < 2.2e-16 ***
Veterinary                                   3.4722e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.032001     Adj. R2: 0.609507
                 Within R2: 0.109605

In [20]:
MEs = ggemmeans(model_hs, terms=c('fac_pub'), typical='median')
MEs

  x      predicted std.error   conf.low  conf.high group
1 NonBSF 0.1456366 0.001300044 0.1430886 0.1481847 1
2 BSF    0.1645401 0.001305936 0.1619805 0.1670997 1

In [21]:
fname = paste0(main_path, "UseBSForNot/predict_rao_1211_hs.csv")
write.csv(MEs, fname, row.names = FALSE)

In [22]:
fml <- as.formula(
  paste0("rao_stirling ~ fac_pub + ", paper_level, "+", journal_level, "+", disciplines, " | author_id + year")
)

model_ss <- feols(fml, data = data[(data$domain_Social.Sciences == 1), ], vcov = "iid")
summary(model_ss)

NOTE: 1 observation removed because of NA values (RHS: 1).

OLS estimation, Dep. Var.: rao_stirling
Observations: 41,437
Fixed-effects: author_id: 13,137,  year: 74
Standard-errors: IID
                                              Estimate Std. Error   t value
fac_pubBSF                                    0.007255   0.001476  4.914008
num_author_log                                0.005099   0.000908  5.618134
num_inst_log                                  0.000551   0.001101  0.500926
num_country_log                              -0.003916   0.001544 -2.536575
num_reference_log                             0.002004   0.000494  4.056738
leadership_global_classallNorth               0.003179   0.001544  2.059010
leadership_global_classallSouth               0.000749   0.002148  0.348754
mean_career_age_log                           0.001538   0.000905  1.698959
inst_h_index_log                              0.001357   0.000559  2.425517
source_h_index_log                            0.000569   0.000374  1.521079
core_sourceCore                               0.004705   0.001566  3.005509
Arts.and.Humanities                           0.000432   0.001310  0.329478
Biochemistry..Genetics.and.Molecular.Biology  0.018389   0.001413 13.012143
Business..Management.and.Accounting           0.002134   0.001416  1.507470
Chemical.Engineering                          0.000529   0.005102  0.103732
Chemistry                                     0.000056   0.001848  0.030491
Computer.Science                              0.015422   0.001219 12.651084
Decision.Sciences                            -0.006285   0.001300 -4.835353
Dentistry                                     0.025002   0.004867  5.137058
Earth.and.Planetary.Sciences                  0.003218   0.001287  2.501073
Economics..Econometrics.and.Finance           0.003553   0.001297  2.739970
Energy                                        0.025423   0.003073  8.271847
Engineering                                   0.005953   0.001077  5.527019
Environmental.Science                         0.013891   0.001212 11.464134
Health.Professions                            0.005642   0.001485  3.798322
Immunology.and.Microbiology                  -0.010498   0.006090 -1.723739
Materials.Science                             0.000333   0.001562  0.212967
Mathematics                                   0.018047   0.001574 11.462605
Medicine                                      0.009208   0.001163  7.915028
Neuroscience                                  0.000998   0.001583  0.630358
Nursing                                       0.017044   0.004383  3.888704
Pharmacology..Toxicology.and.Pharmaceutics    0.006373   0.004282  1.488441
Physics.and.Astronomy                         0.007298   0.001131  6.450974
Psychology                                   -0.003750   0.001212 -3.093747
Social.Sciences                               0.002403   0.000998  2.408119
Veterinary                                    0.009088   0.007820  1.162022
                                               Pr(>|t|)
fac_pubBSF                                   8.9733e-07 ***
num_author_log                               1.9485e-08 ***
num_inst_log                                 6.1643e-01
num_country_log                              1.1200e-02 *
num_reference_log                            4.9897e-05 ***
leadership_global_classallNorth              3.9502e-02 *
leadership_global_classallSouth              7.2728e-01
mean_career_age_log                          8.9338e-02 .
inst_h_index_log                             1.5293e-02 *
source_h_index_log                           1.2825e-01
core_sourceCore                              2.6537e-03 **
Arts.and.Humanities                          7.4180e-01
Biochemistry..Genetics.and.Molecular.Biology  < 2.2e-16 ***
Business..Management.and.Accounting          1.3170e-01
Chemical.Engineering                         9.1738e-01
Chemistry                                    9.7568e-01
Computer.Science                              < 2.2e-16 ***
Decision.Sciences                            1.3361e-06 ***
Dentistry                                    2.8093e-07 ***
Earth.and.Planetary.Sciences                 1.2387e-02 *
Economics..Econometrics.and.Finance          6.1483e-03 **
Energy                                        < 2.2e-16 ***
Engineering                                  3.2860e-08 ***
Environmental.Science                         < 2.2e-16 ***
Health.Professions                           1.4598e-04 ***
Immunology.and.Microbiology                  8.4766e-02 .
Materials.Science                            8.3135e-01
Mathematics                                   < 2.2e-16 ***
Medicine                                     2.5622e-15 ***
Neuroscience                                 5.2847e-01
Nursing                                      1.0101e-04 ***
Pharmacology..Toxicology.and.Pharmaceutics   1.3665e-01
Physics.and.Astronomy                        1.1293e-10 ***
Psychology                                   1.9784e-03 **
Social.Sciences                              1.6041e-02 *
Veterinary                                   2.4524e-01
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.037456     Adj. R2: 0.58094
                 Within R2: 0.031006

In [23]:
MEs = ggemmeans(model_ss, terms=c('fac_pub'), typical='median')
MEs

  x      predicted std.error   conf.low  conf.high group
1 NonBSF 0.2018839 0.005158999 0.1917720 0.2119958 1
2 BSF    0.2091385 0.005249077 0.1988501 0.2194270 1

In [24]:
fname = paste0(main_path, "UseBSForNot/predict_rao_1211_ss.csv")
write.csv(MEs, fname, row.names = FALSE)

In [25]:
paper_vars <- c("num_author_log", "num_inst_log", "num_country_log",
                "num_reference_log", "leadership_global_class",
                "mean_career_age_log", "inst_h_index_log" )


journal_vars <- c("source_h_index_log", "core_source")

disciplines <- c("Arts.and.Humanities", "Biochemistry..Genetics.and.Molecular.Biology", "Business..Management.and.Accounting",
                 "Chemical.Engineering", "Chemistry", "Computer.Science", "Decision.Sciences", "Dentistry",
                 "Earth.and.Planetary.Sciences", "Economics..Econometrics.and.Finance", "Energy", "Engineering",
                 "Environmental.Science + Health.Professions", "Immunology.and.Microbiology", "Materials.Science", "Mathematics",
                 "Medicine", "Neuroscience", "Nursing", "Pharmacology..Toxicology.and.Pharmaceutics", "Physics.and.Astronomy",
                 "Psychology", "Social.Sciences", "Veterinary")

In [26]:
model1 <- model_ps
model2 <- model_ls
model3 <- model_hs
model4 <- model_ss

country_level_reg <- etable(
    list(model1, model2, model3, model4),
    keep = c("fac_pub", paper_vars, journal_vars ),
    se = "iid",
    # cluster = ~ paper_year + paper_field,
    tex = TRUE,
    digits = 3
)

# writeLines(country_level_reg, con = "selfpromt_reg_1014.tex")
country_level_reg

\begingroup
\centering
\begin{tabular}{lcccc}
   \tabularnewline \midrule \midrule
   Dependent Variable: & \multicolumn{4}{c}{rao\_stirling}\\
   Model:                              & (1)                     & (2)                     & (3)                     & (4)\\
   \midrule
   \emph{Variables}\\
   fac\_pubBSF                         & -0.0005$^{***}$         & 0.014$^{***}$           & 0.019$^{***}$           & 0.007$^{***}$\\
                                       & ($8.27\times 10^{-5}$)  & (0.0002)                & (0.0003)                & (0.001)\\
   num\_author\_log                    & $-7.42\times 10^{-5}$   & 0.001$^{***}$           & -0.0002                 & 0.005$^{***}$\\
                                       & ($6.44\times 10^{-5}$)  & (0.0001)                & (0.0002)                & (0.0009)\\
   num\_inst\_log                      & 0.0008$^{***}$          & 0.002$^{***}$           & 0.002$^{***}$           & 0.0006\\
                                       & ($8.24\times 10^{-5}$)  & (0.0001)                & (0.0002)                & (0.001)\\
   num\_country\_log                   & -0.003$^{***}$          & -0.001$^{***}$          & 0.0001                  & -0.004$^{**}$\\
                                       & (0.0001)                & (0.0002)                & (0.0003)                & (0.002)\\
   num\_reference\_log                 & 0.003$^{***}$           & 0.002$^{***}$           & 0.002$^{***}$           & 0.002$^{***}$\\
                                       & ($4.07\times 10^{-5}$)  & ($7.81\times 10^{-5}$)  & (0.0001)                & (0.0005)\\
   leadership\_global\_classallNorth   & 0.001$^{***}$           & 0.001$^{***}$           & 0.0004                  & 0.003$^{**}$\\
                                       & (0.0001)                & (0.0003)                & (0.0004)                & (0.002)\\
   leadership\_global\_classallSouth   & 0.0007$^{***}$          & $-4.07\times 10^{-5}$   & 0.0005                  & 0.0007\\
                                       & (0.0002)                & (0.0004)                & (0.0006)                & (0.002)\\
   mean\_career\_age\_log              & 0.0005$^{***}$          & 0.002$^{***}$           & $-1.13\times 10^{-5}$   & 0.002$^{*}$\\
                                       & ($6.76\times 10^{-5}$)  & (0.0001)                & (0.0002)                & (0.0009)\\
   inst\_h\_index\_log                 & -0.0003$^{***}$         & 0.0005$^{***}$          & 0.002$^{***}$           & 0.001$^{**}$\\
                                       & ($5.22\times 10^{-5}$)  & ($9.61\times 10^{-5}$)  & (0.0001)                & (0.0006)\\
   source\_h\_index\_log               & -0.001$^{***}$          & $-4.59\times 10^{-6}$   & 0.0007$^{***}$          & 0.0006\\
                                       & ($3.05\times 10^{-5}$)  & ($5.41\times 10^{-5}$)  & ($8.47\times 10^{-5}$)  & (0.0004)\\
   core\_sourceCore                    & $-1.81\times 10^{-5}$   & 0.0001                  & 0.002$^{***}$           & 0.005$^{***}$\\
                                       & (0.0002)                & (0.0004)                & (0.0006)                & (0.002)\\
   \midrule
   \emph{Fixed-effects}\\
   author\_id                          & Yes                     & Yes                     & Yes                     & Yes\\
   year                                & Yes                     & Yes                     & Yes                     & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                        & 2,321,151               & 729,686                 & 376,452                 & 41,437\\
   R$^2$                               & 0.56251                 & 0.58560                 & 0.64643                 & 0.71489\\
   Within R$^2$                        & 0.13983                 & 0.07881                 & 0.10961                 & 0.03101\\
   \midrule \midrule
   \multicolumn{5}{l}{\emph{IID standard-errors in parentheses}}\\
   \multicolumn{5}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup